version: "3.9"

services:
  recommend-backend:
    build:
      context: ./recommend-backend
    container_name: recommend-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  auth-backend:
    build:
      context: ./auth-backend
    container_name: auth-backend
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - recommend-backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_SPOTIFY_CLIENT_ID: ${VITE_SPOTIFY_CLIENT_ID}
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_SPOTIFY_REDIRECT_URI: ${VITE_SPOTIFY_REDIRECT_URI}
    container_name: vite-frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - auth-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
