version: "3.9"

services:
  recommend-backend:
    build:
      context: ./recommend-backend
    container_name: recommend-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  auth-backend:
    build:
      context: ./auth-backend
    container_name: auth-backend
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - recommend-backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_SPOTIFY_CLIENT_ID: ${VITE_SPOTIFY_CLIENT_ID}
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    container_name: vite-frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - auth-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge




  # postgres:
  #   image: pgvector/pgvector:0.8.0-pg15-bookworm
  #   container_name: pgvector-postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: testdb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #     - ./init:/docker-entrypoint-initdb.d  # for enabling pgvector extension
  # mongo:
  #   image: mongo:8.0.10
  #   container_name: mongo
  #   ports:
  #     - "27017:27017"
  #   env_file:
  #     - .env
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   volumes:
  #     - mongo-data:/data/db
  #   restart: unless-stopped