version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - qdrant
      - keycloak
    restart: unless-stopped
    volumes:
      - ./backend/artifacts:/app/artifacts:ro  # optional, if artifacts change outside Docker

  qdrant:
    image: qdrant/qdrant:v1.14.1
    container_name: qdrant
    ports:
      - "6333:6333"
    env_file:
      - .env
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT__SERVICE__API__KEY}
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped

  mongo:
    image: mongo:8.0.10
    container_name: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  keycloak:
    image: "quay.io/keycloak/keycloak:26.2.5"
    container_name: keycloak
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-export.json
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    command:
      - start-dev
      - --import-realm
      - --health-enabled=true

volumes:
  mongo-data:
  qdrant-data:
